# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup Odin
description: A GitHub action for setting up the Odin language.
author: G'lek Tarssza
branding:
  icon: package
  color: blue
inputs:
  odin-version:
    description: >
      The version of Odin to setup.

      Allowed values are a version specifier of the form `stream-year-month` or
      `latest` where:

      * `stream` defines the release type (valid options: `dev`).
      * `year` is the release year to get as a four digit number.
      * `month` is the release month to get as a two digit number.
    default: latest
  token:
    description: >
      Personal access token (PAT) used to perform API requests. The post-job
      step removes the PAT.
    default: ${{ github.token }}
  add-binary-to-path:
    description: >
      Whether to add the Odin binary to the system path.
    default: true
outputs:
  odin-binary-path:
    description: The path to the Odin binary that was downloaded.
  odin-library-path:
    description: The path to the Odin libraries that were downloaded.
runs:
  using: node20
  main: main.js
  post: post.js
