# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      build-os:
        description: >
          The operating system to build on.

          Valid options are:

           * `linux`
           * `windows`
           * `macos`
        type: string
        required: true
      build-configuration:
        description: >
          The mode to build in.

          Valid options are:

           * `release`
           * `dev`
        type: string
        required: true
    outputs:
      artifact-id:
        description: >
          The ID of the generated artifact containing the build results.
        value: ${{jobs.build.outputs.artifact-id}}
      artifact-name:
        description: >
          The name of the generated artifact containing the build results.
        value: ${{jobs.build.outputs.artifact-name}}
    secrets:
      github-token:
        description: >
          The GitHub access token to use for making GitHub API requests.
        required: false
jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ${{inputs.build-os}}
    strategy:
      fail-fast: true
      matrix:
        build-os:
          - linux
          - windows
          - macos
        build-configuration:
          - release
          - dev
        exclude:
          - build-configuration: ${{(inputs.build-configuration == 'dev' && 'release') || (inputs.build-configuration == 'release' && 'dev') || ''}}
          #-- Don't include Windows in non-Windows builds
          - build-os: ${{(inputs.build-os == 'linux' && 'windows') || (inputs.build-os == 'windows' && '') || (inputs.build-os == 'macos' && 'windows') || ''}}
          #-- Don't include Linux in non-Linux builds
          - build-os: ${{(inputs.build-os == 'linux' && '') || (inputs.build-os == 'windows' && 'linux') || (inputs.build-os == 'macos' && 'linux') || ''}}
          #-- Don't include macOS in non-macOS builds
          - build-os: ${{(inputs.build-os == 'linux' && 'macos') || (inputs.build-os == 'windows' && 'macos') || (inputs.build-os == 'macos' && '') || ''}}
    outputs:
      artifact-id: ${{steps.upload-artifacts.outputs.artifact-id}}
      artifact-name: ${{steps.upload-artifacts.outputs.artifact-name}}
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          lfs: true
          submodules: recursive
      - id: setup-rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          cache: true
          matcher: true
      - id: build
        name: Build
        run: cargo build --locked --profile ${{inputs.build-configuration}} -Z unstable-options --artifact-dir dist/${{inputs.build-configuration}}
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{inputs.build-configuration}}-${{inputs.build-os}}
          path: dist/${{inputs.build-configuration}}
