# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  push:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      github-token:
        description: >
          The GitHub access token to use for making GitHub API requests.
        required: false
jobs:
  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          lfs: true
          submodules: recursive
      - id: setup-rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          cache: true
          matcher: true
      - id: test
        name: Test
        run: cargo test --locked --workspace
